# Site settings
title: Sam Notes
description: Kişisel notlar
url: "https://alpenberger.github.io"
baseurl: "/samnotes"

# Theme
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: default

# Plugins (GitHub Pages uyumlu)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Pagination
paginate: 5
paginate_path: /samnotes/page:num/

# Markdown
markdown: kramdown

# Include pages
include:
  - _pages

# Author
author:
  name: "Sam"
  bio: "Kişisel notlar"
  avatar: "/assets/images/bio-photo.jpg"

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true

  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Archives
category_archive:
  type: liquid
  path: /samnotes/categories/

tag_archive:
  type: liquid
  path: /samnotes/tags/
